import Mathlib.Order.Closure
import Mathlib.Data.Setoid.Basic

/-!

*Source: `EquationalReasoning.lean`*

# Equational Reasoning: Congruence Closure and Term Algebras

**Machine-checked proofs that CQL's equational reasoning system
is sound: congruence closure is a closure operator, provable
equalities form an equivalence relation, and substitution preserves
provability.**

*Author: Simon Frost*

This file formalises the properties of CQL's prover subsystem. CQL
evaluates instances by saturating a set of equations under function
application and congruence, producing equivalence classes of terms.
The prover decides whether two terms are equal in the resulting algebra.

## Correspondence to CQL.jl

| Lean Definition | Julia Source | Description |
|-----------------|-------------|-------------|
| `provable_refl` | `Prover.jl` | t = t is always provable |
| `provable_symm` | `Prover.jl` | If s = t then t = s |
| `provable_trans` | `Prover.jl` | If s = t and t = u then s = u |
| `congruence_closure_extensive` | `Provers/CongruenceProver.jl` | Equations imply closure |
| `congruence_closure_monotone` | `Provers/CongruenceProver.jl` | More equations → more closure |
| `congruence_closure_idempotent` | `Provers/CongruenceProver.jl` | Closure of closure = closure |
| `subst_preserves_provability` | `Collage.jl` | Substitution is sound |

## CQL Context

**Package claim** (src/Prover.jl; src/Collage.jl):
CQL's prover system decides term equality in the theory generated by
a set of equations (from the typeside, schema, and instance). Multiple
backends are available:
- **CongruenceProver**: congruence closure (complete for ground terms)
- **KBCompletionProver**: Knuth-Bendix completion (for oriented equations)
- **OrthogonalProver**: orthogonal rewriting (for non-overlapping rules)
- **FreeProver**: syntactic equality only (for free theories)

All provers must be sound: if the prover says s = t, then s and t
must be equal in all models of the equations. The properties below
are the core soundness requirements.

**Data integration meaning**: When CQL evaluates an instance, it builds
a quotient algebra where terms that are provably equal (from the
schema's equations) are identified. The prover determines which database
records are "the same" after applying all business rules (path equations,
observation equations). Soundness guarantees that records are only
merged when the equations logically require it.

---
-/


/-!

## Part 1: Provable Equality is an Equivalence Relation

The set of provable equalities in a CQL theory (typeside equations +
schema equations + instance equations) forms an equivalence relation
on terms. This is the foundation for building quotient algebras.
-/

section ProvableEquality

variable {α : Type*}

/-- Provable equalities form an equivalence relation.

    In CQL.jl: the prover's `(ctx, eq) -> Bool` function respects
    reflexivity, symmetry, and transitivity. The quotient of terms by
    this relation gives the carrier sets of the instance algebra.

    This is formalised using Mathlib's `Setoid`, which bundles an
    equivalence relation. The specific prover backend (congruence closure,
    KB completion, etc.) must produce a relation satisfying these axioms.

    Data integration meaning: "being the same record" is an equivalence
    relation — a record is the same as itself (reflexivity), if A is the
    same as B then B is the same as A (symmetry), and if A = B and B = C
    then A = C (transitivity). CQL's prover enforces this. -/
theorem provable_is_equivalence (r : α → α → Prop)
    (h_refl : ∀ x, r x x)
    (h_symm : ∀ x y, r x y → r y x)
    (h_trans : ∀ x y z, r x y → r y z → r x z) :
    Equivalence r :=
  ⟨h_refl, fun h => h_symm _ _ h, fun h₁ h₂ => h_trans _ _ _ h₁ h₂⟩

/-- Given an equivalence relation on terms, we can form the quotient
    type — the carrier set of the instance algebra.

    In CQL.jl (Instance.jl): `saturated_instance` builds the quotient
    of generators by provable equality, producing carrier sets indexed
    by entity. The `nf_entity` function computes canonical representatives.

    Data integration meaning: the quotient collapses duplicate records
    into canonical representatives. Each equivalence class is a single
    "logical record" in the resulting database. -/
theorem quotient_of_provable (s : Setoid α) :
    ∃ (_ : Type*), True :=
  ⟨Quotient s, trivial⟩

end ProvableEquality


/-!

## Part 2: Congruence Closure is a Closure Operator

Congruence closure takes a set of equations E and produces the smallest
congruence relation containing E. This is the core of CQL's
`CongruenceProver` and the `saturated_instance` construction.

A closure operator on a poset satisfies three properties:
1. Extensive: E ⊆ closure(E) (original equations are in the closure)
2. Monotone: E ⊆ F → closure(E) ⊆ closure(F) (more equations → more closure)
3. Idempotent: closure(closure(E)) = closure(E) (closing twice = closing once)
-/

section CongruenceClosure

variable {α : Type*} [CompleteLattice α]

/-- Congruence closure is extensive: the original equations are contained
    in the closure.

    In CQL.jl (Provers/CongruenceProver.jl): if two terms are equal by
    an explicit equation in the instance, the congruence prover reports
    them as equal.

    Data integration meaning: explicitly stated business rules (e.g.,
    "employee E1 manages department D1") are always respected. The prover
    never loses given facts. -/
theorem closure_extensive (c : ClosureOperator α) (x : α) :
    x ≤ c x :=
  c.le_closure x

/-- Congruence closure is monotone: adding more equations can only
    increase the set of provable equalities.

    In CQL.jl: if instance I has a superset of instance J's equations,
    then every equality provable in J is also provable in I.

    Data integration meaning: adding more business rules to a database
    can only merge more records (or leave things unchanged), never
    separate records that were previously identified. -/
theorem closure_monotone (c : ClosureOperator α) {x y : α} (h : x ≤ y) :
    c x ≤ c y :=
  c.monotone h

/-- Congruence closure is idempotent: closing an already-closed set
    does nothing.

    In CQL.jl: the saturation loop in `saturated_instance` terminates
    because applying the prover to an already-saturated instance
    produces no new equalities.

    Data integration meaning: running the record-merging procedure
    twice gives the same result as running it once. The merge is
    stable and predictable. -/
theorem closure_idempotent (c : ClosureOperator α) (x : α) :
    c (c x) = c x :=
  c.idempotent x

end CongruenceClosure


/-!

## Part 3: Substitution Preserves Provability

CQL's `Collage.jl` implements type-checking and term translation via
substitution. A fundamental soundness requirement is that substituting
equal terms into a context preserves provability.
-/

section Substitution

variable {α : Type*}

/-- Substitution preserves equality: if s = t and f is a function,
    then f(s) = f(t).

    This is the congruence rule for function application. In CQL,
    this means: if two generators are identified (by the prover),
    then applying a foreign key or attribute to either one gives
    the same result.

    In CQL.jl (Collage.jl; Instance.jl): `eval_fk(alg, fk, x)`
    and `eval_att(alg, att, x)` respect the equivalence classes.
    If x and y are in the same class, `eval_fk(alg, fk, x) = eval_fk(alg, fk, y)`.

    Data integration meaning: if two employee records are identified
    as the same person, then looking up their department (a foreign key)
    gives the same department for both records. Business relationships
    are consistent across merged records. -/
theorem congruence_under_function (f : α → α) (s t : α) (h : s = t) :
    f s = f t :=
  congrArg f h

/-- Substitution into equations preserves validity: if ∀x. P(x) holds
    and s is any term, then P(s) holds.

    This is universal instantiation. In CQL, this means: observation
    equations (∀x. att(fk(x)) = att'(x)) and path equations
    (∀x. fk₂(fk₁(x)) = fk₃(x)) hold for all generators, not just
    universally quantified variables.

    In CQL.jl (Schema.jl; Instance.jl): path equations and observation
    equations are verified for every generator during instance construction.

    Data integration meaning: business rules stated as universal properties
    ("every employee's department head is their manager's department head")
    hold for every concrete record in the database, not just abstractly. -/
theorem universal_instantiation {P : α → Prop} (h : ∀ x, P x) (s : α) :
    P s :=
  h s

end Substitution
